import re

current_file = "app/src/main/java/com/example/language/LanguageManager.kt"

with open(current_file, "r", encoding="utf-8") as f:
    content = f.read()

# Add PT and PL to getLanguageCode
content = content.replace('"it" -> "IT"', '"it" -> "IT"\n                "pt" -> "PT"\n                "pl" -> "PL"')

# Hardcode the new map translations. We will just find `private val translations = mapOf(` to the end of the file, and replace it.
new_map = """private val translations = mapOf(
        // Navigation Tabs
        "tab_inicio" to mapOf("ES" to "INICIO", "GL" to "INICIO", "CA" to "INICI", "EU" to "HASIERA", "FR" to "ACCUEIL", "EN" to "HOME", "DE" to "START", "IT" to "INIZIO", "PT" to "INÍCIO", "PL" to "GŁÓWNA"),
        "tab_calendario" to mapOf("ES" to "CALENDARIO", "GL" to "CALENDARIO", "CA" to "CALENDARI", "EU" to "EUTEGIA", "FR" to "CALENDRIER", "EN" to "CALENDAR", "DE" to "KALENDER", "IT" to "CALENDARIO", "PT" to "CALENDÁRIO", "PL" to "KALENDARZ"),
        "tab_registro" to mapOf("ES" to "REGISTRO", "GL" to "REXISTRO", "CA" to "REGISTRE", "EU" to "ERREGISTROA", "FR" to "REGISTRE", "EN" to "LOG", "DE" to "PROTOKOLL", "IT" to "REGISTRO", "PT" to "REGISTO", "PL" to "DZIENNIK"),
        "tab_ajustes" to mapOf("ES" to "AJUSTES", "GL" to "AXUSTES", "CA" to "AJUSTOS", "EU" to "EZARROPENAK", "FR" to "RÉGLAGES", "EN" to "SETTINGS", "DE" to "EINSTELLUNGEN", "IT" to "IMPOSTAZIONI", "PT" to "DEFINIÇÕES", "PL" to "USTAWIENIA"),

        // Inicio Screen
        "dosis_de_hoy" to mapOf("ES" to "DOSIS DE HOY", "GL" to "DOSE DE HOXE", "CA" to "DOSI D'AVUI", "EU" to "GAURKO DOSIA", "FR" to "DOSE DU JOUR", "EN" to "TODAY'S DOSE", "DE" to "TAGESDOSIS", "IT" to "DOSE DI OGGI", "PT" to "DOSE DE HOJE", "PL" to "DZISIEJSZA DAWKA"),
        "hora_objetivo" to mapOf("ES" to "Hora objetivo", "GL" to "Hora obxectivo", "CA" to "Hora objectiu", "EU" to "Helburu ordua", "FR" to "Heure cible", "EN" to "Target time", "DE" to "Zielzeit", "IT" to "Ora obiettivo", "PT" to "Hora alvo", "PL" to "Czas docelowy"),
        "registrar_toma" to mapOf("ES" to "REGISTRAR TOMA DE HOY", "GL" to "REXISTRAR TOMA DE HOXE", "CA" to "REGISTRAR PRESA D'AVUI", "EU" to "ERREGISTRATU GAURKO TOMA", "FR" to "ENREGISTRER LA PRISE", "EN" to "MARK TODAY'S DOSE TAKEN", "DE" to "DOSIS ALS GENOMMEN EINGEBEN", "IT" to "REGISTRA ASSUNZIONE DI OGGI", "PT" to "REGISTAR DOSE DE HOJE", "PL" to "ZAZNACZ DZISIEJSZĄ DAWKĘ"),
        "toma_registrada" to mapOf("ES" to "TOMA REGISTRADA", "GL" to "TOMA REXISTRADA", "CA" to "PRESA REGISTRADA", "EU" to "TOMA ERREGISTRATUTA", "FR" to "PRISE ENREGISTRÉE", "EN" to "DOSE LOGGED", "DE" to "EINNAHME ERFASST", "IT" to "ASSUNZIONE REGISTRATA", "PT" to "DOSE REGISTADA", "PL" to "DAWKA ZAPISANA"),
        "prueba_inr_en" to mapOf("ES" to "Prueba de INR en", "GL" to "Proba de INR en", "CA" to "Prova d'INR en", "EU" to "INR froga", "FR" to "Test INR dans", "EN" to "INR check in", "DE" to "INR-Test in", "IT" to "Test INR tra", "PT" to "Teste INR em", "PL" to "Badanie INR za"),
        "dias" to mapOf("ES" to "días", "GL" to "días", "CA" to "dies", "EU" to "egun", "FR" to "jours", "EN" to "days", "DE" to "Tagen", "IT" to "giorni", "PT" to "dias", "PL" to "dni"),
        "hoy" to mapOf("ES" to "¡Hoy!", "GL" to "¡Hoxe!", "CA" to "¡Avui!", "EU" to "Gaur!", "FR" to "Aujourd'hui !", "EN" to "Today!", "DE" to "Heute!", "IT" to "Oggi!", "PT" to "Hoje!", "PL" to "Dzisiaj!"),
        "proxima_prueba_inr" to mapOf("ES" to "Próxima prueba de INR", "GL" to "Próxima proba de INR", "CA" to "Propera prova d'INR", "EU" to "Hurrengo INR froga", "FR" to "Prochain contrôle INR", "EN" to "Next INR lab test", "DE" to "Nächster INR-Test", "IT" to "Prossimo test INR", "PT" to "Próximo teste INR", "PL" to "Następne badanie INR"),
        "ultimos_14_dias" to mapOf("ES" to "ÚLTIMOS 14 DÍAS", "GL" to "ÚLTIMOS 14 DÍAS", "CA" to "ÚLTIMS 14 DIES", "EU" to "AZKEN 14 EGUNAK", "FR" to "14 DERNIERS JOURS", "EN" to "PAST 14 DAYS", "DE" to "LETZTE 14 TAGE", "IT" to "ULTIMI 14 GIORNI", "PT" to "ÚLTIMOS 14 DIAS", "PL" to "OSTATNIE 14 DNI"),
        "registro_reciente" to mapOf("ES" to "REGISTRO RECIENTE", "GL" to "REXISTRO RECENTE", "CA" to "REGISTRE RECENT", "EU" to "AZKEN ERREGISTROA", "FR" to "REGISTRE RÉCENT", "EN" to "RECENT LOG", "DE" to "LETZTE EINTRÄGE", "IT" to "REGISTRO RECENTE", "PT" to "REGISTO RECENTE", "PL" to "OSTATNI DZIENNIK"),
        "ver_todo" to mapOf("ES" to "VER TODO", "GL" to "VER TODO", "CA" to "VEURE TOT", "EU" to "DENA IKUSI", "FR" to "VOIR TOUT", "EN" to "VIEW ALL", "DE" to "ALLE ANZEIGEN", "IT" to "MOSTRA TUTTO", "PT" to "VER TUDO", "PL" to "ZOBACZ WSZYSTKO"),

        // Calendario Screen
        "importar_pauta" to mapOf("ES" to "IMPORTAR PAUTA", "GL" to "IMPORTAR PAUTA", "CA" to "IMPORTAR PAUTA", "EU" to "PAUTA INPORTATU", "FR" to "IMPORTER PRESCRIPTION", "EN" to "IMPORT SCHEDULE", "DE" to "PLAN IMPORTIEREN", "IT" to "IMPORTA PIANO", "PT" to "IMPORTAR PLANO", "PL" to "IMPORTUJ HARMONOGRAM"),
        "subir_foto_pdf" to mapOf("ES" to "Subir foto o PDF de la pauta mensual (procesado offline en el dispositivo)", "GL" to "Subir foto ou PDF da pauta mensual (procesado offline no dispositivo)", "CA" to "Penjar foto o PDF de la pauta mensual (processat offline al dispositiu)", "EU" to "Igo hileroko pautaren argazkia edo PDFa (lineaz kanpo prozesatua)", "FR" to "Charger photo ou PDF de l'ordonnance mensuelle (traité hors-ligne)", "EN" to "Upload photo or PDF of monthly schedule (offline processing on device)", "DE" to "Foto oder PDF des Monatsplans hochladen (offline verarbeitet)", "IT" to "Carica foto o PDF del piano mensile (elaborato offline)", "PT" to "Carregar foto ou PDF do plano mensal (processamento offline no dispositivo)", "PL" to "Prześlij zdjęcie lub PDF miesięcznego planu (przetwarzanie offline na urządzeniu)"),
        "toca_para_adjuntar" to mapOf("ES" to "Toca para adjuntar", "GL" to "Toca para adxuntar", "CA" to "Toca per adjuntar", "EU" to "Sakatuk erantsitzeko", "FR" to "Appuyer pour joindre", "EN" to "Tap to attach file", "DE" to "Tippen zum Anhängen", "IT" to "Tocca per allegare", "PT" to "Toque para anexar", "PL" to "Dotknij, aby dołączyć"),
        "editar_dosis" to mapOf("ES" to "EDITAR DOSIS", "GL" to "EDITAR DOSE", "CA" to "EDITAR DOSI", "EU" to "DOSIA EDITATU", "FR" to "MODIFIER LA DOSE", "EN" to "EDIT DOSE", "DE" to "DOSIS BEARBEITEN", "IT" to "MODIFICA DOSE", "PT" to "EDITAR DOSE", "PL" to "EDYTUJ DAWKĘ"),
        "editar_inr" to mapOf("ES" to "EDITAR INR", "GL" to "EDITAR INR", "CA" to "EDITAR INR", "EU" to "INR EDITATU", "FR" to "MODIFIER L'INR", "EN" to "EDIT INR", "DE" to "INR BEARBEITEN", "IT" to "MODIFICA INR", "PT" to "EDITAR INR", "PL" to "EDYTUJ INR"),
        "cita_inr" to mapOf("ES" to "Cita INR", "GL" to "Cita INR", "CA" to "Cita INR", "EU" to "INR Hitzordua", "FR" to "Rdv INR", "EN" to "INR Appt", "DE" to "INR-Termin", "IT" to "Appuntamento INR", "PT" to "Consulta INR", "PL" to "Wizyta INR"),

        // Registro Screen & Stats
        "historial" to mapOf("ES" to "HISTORIAL DE TOMAS", "GL" to "HISTORIAL DE TOMAS", "CA" to "HISTORIAL DE PRESA", "EU" to "TOMEN HISTORIALA", "FR" to "HISTORIQUE DES PRISES", "EN" to "DOSE HISTORY", "DE" to "EINNAHME-HISTORIE", "IT" to "CRONOLOGIA ASSUNZIONI", "PT" to "HISTÓRICO DE DOSES", "PL" to "HISTORIA DAWEK"),
        "estadisticas" to mapOf("ES" to "ESTADÍSTICAS", "GL" to "ESTADÍSTICAS", "CA" to "ESTADÍSTIQUES", "EU" to "ESTATISTIKAK", "FR" to "STATISTIQUES", "EN" to "STATISTICS", "DE" to "STATISTIKEN", "IT" to "STATISTICHE", "PT" to "ESTATÍSTICAS", "PL" to "STATYSTYKI"),
        "exportar_registro" to mapOf("ES" to "EXPORTAR REGISTRO EN PDF", "GL" to "EXPORTAR REXISTRO EN PDF", "CA" to "EXPORTAR REGISTRE EN PDF", "EU" to "EXPORTATU ERREGISTROA PDF-N", "FR" to "EXPORTER LE REGISTRE EN PDF", "EN" to "EXPORT LOG TO PDF", "DE" to "PROTOKOLL ALS PDF EXPORTIEREN", "IT" to "ESPORTA REGISTRO IN PDF", "PT" to "EXPORTAR REGISTO PARA PDF", "PL" to "EKSPORTUJ DZIENNIK DO PDF"),
        "desde" to mapOf("ES" to "DESDE", "GL" to "DENDE", "CA" to "DES DE", "EU" to "NOIZTIK", "FR" to "DEPUIS", "EN" to "FROM", "DE" to "VON", "IT" to "DA", "PT" to "DE", "PL" to "OD"),
        "hasta" to mapOf("ES" to "HASTA", "GL" to "ATÉ", "CA" to "FINS A", "EU" to "NORA", "FR" to "JUSQU'À", "EN" to "TO", "DE" to "BIS", "IT" to "A", "PT" to "ATÉ", "PL" to "DO"),
        "exportar_pdf_btn" to mapOf("ES" to "EXPORTAR PDF", "GL" to "EXPORTAR PDF", "CA" to "EXPORTAR PDF", "EU" to "EXPORTATU PDF", "FR" to "EXPORTER PDF", "EN" to "EXPORT PDF", "DE" to "PDF EXPORTIEREN", "IT" to "ESPORTA PDF", "PT" to "EXPORTAR PDF", "PL" to "EKSPORTUJ PDF"),
        "puntual" to mapOf("ES" to "Puntual", "GL" to "Puntual", "CA" to "Puntual", "EU" to "Puntuak", "FR" to "À l'heure", "EN" to "On time", "DE" to "Pünktlich", "IT" to "Puntuale", "PT" to "Pontual", "PL" to "Punktualnie"),
        "retraso" to mapOf("ES" to "Retraso (+-2h)", "GL" to "Atraso (+-2h)", "CA" to "Retard (+-2h)", "EU" to "Atzerapena", "FR" to "Retard (+-2h)", "EN" to "Delay (+-2h)", "DE" to "Verzögerung", "IT" to "Ritardo", "PT" to "Atraso (+-2h)", "PL" to "Opóźnienie (+-2h)"),
        "pendiente" to mapOf("ES" to "Pendiente", "GL" to "Pendente", "CA" to "Pendent", "EU" to "Zain", "FR" to "En attente", "EN" to "Pending", "DE" to "Ausstehend", "IT" to "In attesa", "PT" to "Pendente", "PL" to "Oczekujące"),
        "falta" to mapOf("ES" to "Sin registrar / Falta", "GL" to "Sen mecer / Falta", "CA" to "Falta / Sense registrar", "EU" to "Aukeratu gabe / Falta", "FR" to "Non enregistré / Manqué", "EN" to "Missed / Unlogged", "DE" to "Ausgefallen / Nicht erfasst", "IT" to "Mancata assunzione", "PT" to "Não registado / Falta", "PL" to "Pominięte / Niezapisane"),
        "inr_promedio_ano" to mapOf("ES" to "INR Promedio del año", "GL" to "INR Promedio do ano", "CA" to "INR Mitjà de l'any", "EU" to "Urteko Batez besteko INR", "FR" to "INR Moyenne annuelle", "EN" to "Average yearly INR", "DE" to "Jahresdurchschnitts-INR", "IT" to "INR Medio annuale", "PT" to "INR Médio anual", "PL" to "Średnie roczne INR"),
        "tiempo_en_rango" to mapOf("ES" to "Tiempo en rango objetivo (TTR)", "GL" to "Tempo en rango obxectivo (TTR)", "CA" to "Temps en rang objectiu (TTR)", "EU" to "Helburu barrutian denbora", "FR" to "Temps dans la cible (TTR)", "EN" to "Time in Target Range (TTR)", "DE" to "Zeit im Zielbereich (TTR)", "IT" to "Tempo in target (TTR)", "PT" to "Tempo no intervalo alvo (TTR)", "PL" to "Czas w zakresie docelowym (TTR)"),

        // Ajustes Screen
        "recordatorio_hora" to mapOf("ES" to "Hora del recordatorio", "GL" to "Hora do lembrete", "CA" to "Hora del recordatori", "EU" to "Gogorarazteko ordua", "FR" to "Heure du rappel", "EN" to "Reminder time", "DE" to "Erinnerungszeit", "IT" to "Ora del promemoria", "PT" to "Hora do lembrete", "PL" to "Czas przypomnienia"),
        "notificaciones" to mapOf("ES" to "Notificaciones de la toma", "GL" to "Notificacións da toma", "CA" to "Notificacions de la presa", "EU" to "Jakinarazpenak", "FR" to "Rappels de prise", "EN" to "Dose notifications", "DE" to "Einnahme-Benachrichtigungen", "IT" to "Notifiche assunzione", "PT" to "Notificações de dose", "PL" to "Powiadomienia o dawce"),
        "monitorizacion" to mapOf("ES" to "MONITORIZACIÓN", "GL" to "MONITORIZACIÓN", "CA" to "MONITORITZACIÓ", "EU" to "MONITORIZAZIOA", "FR" to "SURVEILLANCE", "EN" to "MONITORING", "DE" to "ÜBERWACHUNG", "IT" to "MONITORAGGIO", "PT" to "MONITORIZAÇÃO", "PL" to "MONITOROWANIE"),
        "frecuencia_inr" to mapOf("ES" to "Frecuencia control INR", "GL" to "Frecuencia control INR", "CA" to "Freqüència control INR", "EU" to "INR kontrol maiztasuna", "FR" to "Fréquence des contrôles INR", "EN" to "INR check frequency", "DE" to "INR-Kontrollfrequenz", "IT" to "Frequenza controllo INR", "PT" to "Frequência de controlo INR", "PL" to "Częstotliwość badań INR"),
        "frecuencia_mensual" to mapOf("ES" to "Mensual", "GL" to "Mensual", "CA" to "Mensual", "EU" to "Hilero", "FR" to "Mensuelle", "EN" to "Monthly", "DE" to "Monatlich", "IT" to "Mensile", "PT" to "Mensal", "PL" to "Miesięcznie"),
        "frecuencia_semanal" to mapOf("ES" to "Semanal", "GL" to "Semanal", "CA" to "Setmanal", "EU" to "Astero", "FR" to "Hebdomadaire", "EN" to "Weekly", "DE" to "Wöchentlich", "IT" to "Settimanale", "PT" to "Semanal", "PL" to "Tygodniowo"),
        "frecuencia_quincenal" to mapOf("ES" to "Quincenal", "GL" to "Quincenal", "CA" to "Quinzenal", "EU" to "Hamabostero", "FR" to "Bimensuelle", "EN" to "Fortnightly", "DE" to "Zweiwöchentlich", "IT" to "Quindicinale", "PT" to "Quinzenal", "PL" to "Co dwa tygodnie"),
        "frecuencia_automatica" to mapOf("ES" to "Automática (con calendario)", "GL" to "Automática (co calendario)", "CA" to "Automàtica (amb el calendari)", "EU" to "Automatikoa (egutegiarekin)", "FR" to "Automatique (synchro calendrier)", "EN" to "Automatic (synced with schedule)", "DE" to "Automatisch (Kalender-Sync)", "IT" to "Automatica (sincro calendario)", "PT" to "Automática (sinc. com calendário)", "PL" to "Automatycznie (synchr. z kalendarzem)"),
        "dia_preferido" to mapOf("ES" to "Día preferido de revisión", "GL" to "Día preferido de revisión", "CA" to "Dia preferit de revisió", "EU" to "Berrikuspen eguna", "FR" to "Jour de contrôle préféré", "EN" to "Preferred check day", "DE" to "Bevorzugter Kontrolltag", "IT" to "Giorno di controllo preferito", "PT" to "Dia preferido de controlo", "PL" to "Preferowany dzień kontroli"),
        "gestionar_medicacion" to mapOf("ES" to "Gestionar medicación", "GL" to "Xestionar medicación", "CA" to "Gestionar medicació", "EU" to "Medikazioa kudeatu", "FR" to "Gérer le traitement", "EN" to "Manage medication", "DE" to "Medikation verwalten", "IT" to "Gestisci farmaco", "PT" to "Gerir medicação", "PL" to "Zarządzaj lekami"),
        "rango_objetivo_inr" to mapOf("ES" to "Rango objetivo INR", "GL" to "Rango obxectivo INR", "CA" to "Rang objectiu INR", "EU" to "INR helburu tartea", "FR" to "Cible INR", "EN" to "INR Target Range", "DE" to "INR-Zielbereich", "IT" to "Intervallo target INR", "PT" to "Intervalo alvo INR", "PL" to "Zakres docelowy INR"),
        "apariencia" to mapOf("ES" to "APARIENCIA", "GL" to "APARIENCIA", "CA" to "APARENÇA", "EU" to "ITXURA", "FR" to "APPARENCE", "EN" to "APPEARANCE", "DE" to "ERSCHEINUNGSBILD", "IT" to "ASPETTO", "PT" to "APARÊNCIA", "PL" to "WYGLĄD"),
        "tema" to mapOf("ES" to "Tema", "GL" to "Tema", "CA" to "Tema", "EU" to "Gaia", "FR" to "Thème", "EN" to "Theme", "DE" to "Design", "IT" to "Tema", "PT" to "Tema", "PL" to "Motyw"),
        "tema_claro" to mapOf("ES" to "Claro", "GL" to "Claro", "CA" to "Clar", "EU" to "Argia", "FR" to "Clair", "EN" to "Light", "DE" to "Hell", "IT" to "Chiaro", "PT" to "Claro", "PL" to "Jasny"),
        "tema_oscuro" to mapOf("ES" to "Oscuro", "GL" to "Escuro", "CA" to "Fosc", "EU" to "Iluna", "FR" to "Sombre", "EN" to "Dark", "DE" to "Dunkel", "IT" to "Scuro", "PT" to "Escuro", "PL" to "Ciemny"),
        "tema_sistema" to mapOf("ES" to "Sistema", "GL" to "Sistema", "CA" to "Sistema", "EU" to "Sistema", "FR" to "Système", "EN" to "System", "DE" to "System", "IT" to "Sistema", "PT" to "Sistema", "PL" to "System"),
        "idioma" to mapOf("ES" to "Idioma", "GL" to "Idioma", "CA" to "Idioma", "EU" to "Hizkuntza", "FR" to "Langue", "EN" to "Language", "DE" to "Sprache", "IT" to "Lingua", "PT" to "Idioma", "PL" to "Język"),
        "idioma_app" to mapOf("ES" to "Idioma de la app", "GL" to "Idioma da app", "CA" to "Idioma de l'aplicació", "EU" to "Aplikazioaren hizkuntza", "FR" to "Langue de l'application", "EN" to "App language", "DE" to "App-Sprache", "IT" to "Lingua dell'app", "PT" to "Idioma da app", "PL" to "Język aplikacji"),
        "datos" to mapOf("ES" to "DATOS", "GL" to "DATOS", "CA" to "DADES", "EU" to "DATUAK", "FR" to "DONNÉES", "EN" to "DATA", "DE" to "DATEN", "IT" to "DATI", "PT" to "DADOS", "PL" to "DANE"),
        "formato_fecha" to mapOf("ES" to "Formato de fecha", "GL" to "Formato de data", "CA" to "Format de data", "EU" to "Data formatua", "FR" to "Format de date", "EN" to "Date format", "DE" to "Datumsformat", "IT" to "Formato data", "PT" to "Formato de data", "PL" to "Format daty"),
        "periodo_exportacion" to mapOf("ES" to "Periodo de exportación", "GL" to "Periodo de exportación", "CA" to "Període d'exportació", "EU" to "Exportatze epea", "FR" to "Période d'exportation", "EN" to "Default export period", "DE" to "Exportzeitraum", "IT" to "Periodo di esportazione", "PT" to "Período de exportação", "PL" to "Okres eksportu")
    )
}"""

content = re.sub(r'private val translations = mapOf\([\s\S]*\}\s*$', new_map, content)

with open(current_file, "w", encoding="utf-8") as f:
    f.write(content)
